[package]
name = "kpasim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfrob = "0.2.1"
tinyvec = { version = "1.6.0", features = ["rustc_1_57"] }
